source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rake', '~> 10.3.0'
gem 'dotenv'
gem 'spork'
gem 'rspec', '>= 3.4.0'
gem 'rspec-retry'
gem 'selenium-webdriver', '>= 2.47.1'
gem 'rest-client'
gem 'ci_reporter_rspec'
gem 'rspec-legacy_formatters'
gem 'spec_upon_a_time'
gem 'faker'
gem 'net-ssh'
gem 'link_header'
gem 'allure-rspec', '>= 0.6.9'
gem 'logging'
gem 'mail'
gem 'rubyzip', '>= 1.0.0'